version: '3'

services:
  jenkins-swarm:
    image: joalherrero/jenkins-swarm
    ports:
     - 8080
     - 5000
    volumes:
     - jenkins-data:/var/jenkins_home
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role != manager]

volumes:
  jenkins-data:

networks:
  stack-automate:  
